# Generated by Django 2.0.2 on 2018-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180602_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='images',
            new_name='image',
        ),
    ]
